name: reviewdog
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Add pip bin to PATH
        run: echo "/home/runner/.local/bin" >> $GITHUB_PATH

      - name: Install deps
        run: pip install ".[ci]"

      - name: Reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make reviewdog
